name: Laravel & React CI

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    name: Laravel Backend Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: ./snackies-server

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: ./snackies-server

      - name: Generate key
        run: php artisan key:generate
        working-directory: ./snackies-server

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./snackies-server

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test
        working-directory: ./snackies-server

  react-build:
    name: React Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./snackies-client

      - run: npm ci
        working-directory: ./snackies-client

      - run: npm run build --if-present
        working-directory: ./snackies-client

      - run: npm test
        working-directory: ./snackies-client
